//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Davis.LiveChat.Logic.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public System.Guid Guid { get; set; }
        public string SentUserName { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SentDateTime { get; set; }
    }
}
